apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
  labels:
    name: ingress-hosts
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress", ... }  # Paste the full Ingress resource JSON here
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
    - app.notjustdevops.com
    - simple.notjustdevops.com
    - java.notjustdevops.com
    - notjustdevops.com
    secretName: app-tls  # Add the secretName to store the SSL/TLS certificate
  rules:
  - host: notjustdevops.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: main
            port:
              number: 5000
  - host: simple.notjustdevops.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: simple
            port:
              number: 5000
  - host: java.notjustdevops.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: java
            port:
              number: 8080
  - host: app.notjustdevops.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app
            port:
              number: 5000
